---
- hosts: localhost
  roles:
    - role: '{{ playbook_dir }}'
      vars:
        gri_installs:
          - repo: bradfordwagner/go-azure-blob-cli
            binary_name: abc
            tag: 1.2.1
  tasks:
    - name: check binaries installed
      include_tasks: ./tests/check_output.yml
      loop_control:
        loop_var: item
      loop:
        - 'ls -lh /usr/local/bin'
        - 'ls -lh /usr/local/go-azure-blob-cli/1.2.1'
        - /usr/local/bin/abc -h
