---
- hosts: localhost
  roles:
    - role: '{{ playbook_dir }}'
      vars:
        gri_installs:
          # - repo: bradfordwagner/go-azure-blob-cli
          #   binary_name: abc
          #   tag: 1.2.1
          # - repo: bradfordwagner/ks
          #   # binary_name: ks
          #   tag: 1.10.1
          - repo: bradfordwagner/gh-template-go-cli
            binary_name: testcli
            tag: v1.6.0-beta1
            # tag: v1.5.1
  tasks:
    - name: check binaries installed
      include_tasks: ./tests/check_output.yml
      loop_control:
        loop_var: item
      loop:
        - ls -lh /usr/local/bin
        - /usr/local/bin/testcli
        # - /usr/local/bin/ks -h
        # - ls -lh /usr/local/go-azure-blob-cli/1.2.1
        # - /usr/local/go-azure-blob-cli/1.2.1/abc -h
        # - /usr/local/bin/abc -h
