---
- hosts: localhost
  roles:
    - role: '{{ playbook_dir }}'
      vars:
        gri_formats:
          pack: |
            {{- app_repo | lower }}{{ app_separator }}{{ app.tag | lower }}{{ app_separator }}{{ gri_os | lower -}}
            {% if 'amd64' != gri_arch %}
            {{ app_separator }}{{ gri_arch | lower -}}
            {% endif %}
            .{{ app_archive_extension -}}
        gri_installs:
          - repo: bradfordwagner/go-azure-blob-cli
            binary_name: abc
            tag: 1.3.0
          - repo: bradfordwagner/gh-template-go-cli
            binary_name: testcli
            tag: v1.6.0
          - repo: bradfordwagner/ks
            tag: 1.11.0
          - repo: buildpacks/pack
            checksum_style: sha256
            tag: v0.34.2
            separator: '-'
            archive_key: pack
            archive_extension: tgz

  tasks:
    - name: check binaries installed
      include_tasks: ./tests/check_output.yml
      loop_control:
        loop_var: item
      loop:
         - pack -h
         - abc -h
         - ks -h
         - testcli -h
