- set_fact:
    app_checksum_style: '{{ app.checksum_style | default(gri_checksum_style) }}'
    app_meta: '{{ app.meta | default({}) }}' # string custom metadata for templating
    app_org: "{{ app.repo.split('/') | first | lower }}"
    app_repo: "{{ app.repo.split('/') | last | lower }}"
    app_separator: "{{ app.separator | default(gri_separator) }}"
    app_archive_extension: '{{ app.archive_extension | default(gri_archive_extension) }}'
    app_archive_key: '{{ app.archive_key | default("") }}'

- set_fact:
    app_archive_format: '{{ gri_formats[app_archive_key] | default(gri_default_archive_format) | trim }}'
    app_binary_name: '{{ app.binary_name | default(app_repo) }}' # binary to name to install from archive
    app_url: '{{ gri_mirror }}/{{ app.repo }}/releases/download/{{ app.tag }}'
    fs_app_install_dir: '{{ gri_parent_install_dir }}/{{ app_repo }}/{{ app.tag }}'

- set_fact:
    app_tgz_url: '{{ app_url }}/{{ app_archive_format }}'
    fs_app_install_exe: '{{ fs_app_install_dir }}/{{ app_binary_name }}'
    fs_app_link: '{{ gri_link_dir }}/{{ app_binary_name }}'
    fs_tmp_tgz: '/tmp/{{ app_archive_format }}'

- debug:
    msg:
      - app_org={{ app_org }}
      - app_repo={{ app_repo }}
      - app_separator={{ app_separator }}
      - app_tag={{ app.tag }}
      - app_tgz_url={{ app_tgz_url }}
      - app_url={{ app_url }}
      - fs_app_install_dir={{ fs_app_install_dir }}
      - fs_app_install_exe={{ fs_app_install_exe }}
      - fs_tmp_tgz={{ fs_tmp_tgz }}

#- meta: end_play

- name: check for {{ fs_app_install_dir }}
  stat:
    path: '{{ fs_app_install_exe }}'
  changed_when: false
  register: app_binary
- when: not app_binary.stat.exists
  block:
    # resolve checksum
    - include_tasks: '{{ app_checksum_style }}.yml'

    # download and install
    - name: download {{ app_tgz_url }}
      get_url:
        url: '{{ app_tgz_url }}'
        dest: '{{ fs_tmp_tgz }}'
        checksum: 'sha256:{{ checksum }}'
        mode: 644
    - name: mkdir {{ fs_app_install_dir }}
      file:
        path: '{{ fs_app_install_dir }}'
        state: directory
        mode: '755'
    - name: unarchive {{ fs_tmp_tgz }}
      unarchive:
        remote_src: true
        src: '{{ fs_tmp_tgz }}'
        dest: '{{ fs_app_install_dir }}'
        creates: '{{ fs_app_install_exe }}'
        mode: '755'
  # cleanup tgz file
  always:
    - name: rm {{ fs_tmp_tgz }}
      file:
        path: '{{ fs_tmp_tgz }}'
        state: absent
- name: link {{ fs_app_link }} to {{ fs_app_install_exe }}
  file:
    src: '{{ fs_app_install_exe }}'
    dest: '{{ fs_app_link }}'
    state: link
    force: true # override existing symlink
