---
# tasks file for go-releaser-install
- include_role:
    name: andrewrothstein.unarchivedeps

- name: install apps
  include_tasks: install_binary.yml
  loop: '{{ gri_installs }}'
  loop_control:
    loop_var: app
