- set_fact:
    app_checksum_url: '{{ app_tgz_url }}.sha256'
- debug:
    msg:
      - app_checksum_url={{ app_checksum_url }}

# resolve checksum
- name: get checksums from {{ app_checksum_url }}
  uri:
    # eg https://github.com/rumstead/gitops-toolkit/releases/download/v1.1.2/checksums.txt
    url: '{{ app_checksum_url }}'
    return_content: yes
  register: checksum_response
- name: set checksum content fact
  set_fact:
    checksum_content: "{{ checksum_response.content }}"
- name: resolve checksum
  set_fact:
    checksum: "{{ item.split()[0] }}"
  when: app_tgz in item
  with_items: "{{ checksum_content.split('\n') }}"
